### ISSUE TITLE
LIQUID_TOKENS and ILLIQUID_TOKENS are wrong

### ISSUE THREAD

**Issue by clar** [AventusSystems/token-sale#2]
uint public constant LIQUID_TOKENS = 2500000 ether;
    uint public constant ILLIQUID_TOKENS = 1500000 ether;

**Comment by AlanVey** [comment]
Thanks, we are still in the process of finalising exactly what these figures will be but there is unlikely to be any more than 8,000,000 AVT in circulation before at least 1 year has passed.
